use_frameworks!

target 'AutoScrollCollectionView_Example' do
  pod 'AutoScrollCollectionView', :path => '../'

  target 'AutoScrollCollectionView_Tests' do
    inherit! :search_paths

    
  end
end
